import type { MovementTemplate } from "../schema";

/**
 * Seated Bicep Curl. Camera in front (or slightly to the side); shoulder, elbow and wrist in
 * frame. Primary metric: the elbow's interior angle (shoulder-elbow-wrist). Rest ~170 degrees
 * (arm hanging), peak ~60 degrees (hand toward shoulder).
 */
export const seatedBicepCurl: MovementTemplate = {
  id: "seated-bicep-curl",
  version: 2,
  name: "Seated Bicep Curl",
  description: "Sit upright, bend your elbow to curl your hand toward your shoulder, then lower it under control.",
  category: "Upper Body",
  difficulty: "Beginner",
  bodyPart: "Elbow",
  bodySegment: "upper",
  primaryJoint: "elbow",
  movement: "flexion",
  defaultReps: 10,
  instructions: [
    "Sit upright in front of your camera.",
    "Keep your shoulder, elbow and wrist in view.",
    "Curl your hand up toward your shoulder, keeping your elbow by your side.",
    "Lower your arm smoothly back to the start.",
  ],
  camera: {
    view: "either",
    minBodyFraction: 0.14,
    maxBodyFraction: 0.85,
    hint: "Front or slightly side-on, about 1 to 2 m away, so shoulder, elbow and wrist are in view.",
    segmentWord: "arm",
  },
  sideMode: "auto",
  landmarks: {
    // The hip is required because "trunk lean" is a mandatory rule: a curl cannot be called good while it cannot be checked.
    required: [{ joint: "shoulder" }, { joint: "elbow" }, { joint: "wrist" }, { joint: "hip" }],
    optional: [],
  },
  metrics: {
    elbow: { kind: "angle", a: { joint: "shoulder" }, b: { joint: "elbow" }, c: { joint: "wrist" } },
    upperArm: { kind: "fromVertical", a: { joint: "shoulder" }, b: { joint: "elbow" } },
    trunk: { kind: "fromVertical", a: { joint: "shoulder" }, b: { joint: "hip" } },
  },
  setup: {
    instruction: "Sit tall with your arm hanging by your side.",
    holdMs: 900,
    conditions: [{ metric: "upperArm", max: 30 }],
  },
  phaseLabels: { rest: "Ready", out: "Curling up", peak: "Top", back: "Lowering" },
  phaseCues: {
    rest: "Ready. Curl your hand toward your shoulder.",
    out: "Keep curling, elbow by your side.",
    peak: "Good. Squeeze briefly, then lower.",
    back: "Lower your arm slowly.",
  },
  rep: {
    metric: "elbow",
    direction: "decrease",
    restThreshold: 140,
    leaveThreshold: 125,
    countThreshold: 95,
    peakThreshold: 72,
    returnDrop: 12,
    minRepMs: 1600,
    maxRepMs: 14000,
    debounceMs: 800,
    returnStallMs: 3500,
    abandonMs: 25000,
    unit: "deg",
  },
  repRules: {
    range: {
      id: "insufficient_curl",
      label: "Elbow not bent fully",
      severity: "minor",
      invalidatesRep: true,
      landmarks: [{ joint: "elbow" }, { joint: "wrist" }],
      bones: [[{ joint: "elbow" }, { joint: "wrist" }]],
      low: {
        show: "Curl a little higher",
        observation: "the hand stopped before it reached the top of the curl",
        texts: [
          "Curl your hand a little higher toward your shoulder.",
          "Bring your wrist closer to your shoulder at the top of the curl.",
          "Take your time and curl your hand as high as is comfortable.",
        ],
      },
      ack: "Good, that was a fuller curl.",
    },
    tooFast: {
      id: "too_fast",
      label: "Moved too quickly",
      severity: "minor",
      invalidatesRep: false,
      landmarks: [{ joint: "elbow" }],
      low: {
        show: "Slow down",
        observation: "the repetition was quicker than the controlled pace",
        texts: [
          "Slow down. Take about two seconds to curl your hand up.",
          "Lower your arm more slowly and keep control of the weight of your arm.",
          "Count two seconds as your arm curls up and two as it lowers.",
        ],
      },
      ack: "Nice, that was a controlled pace.",
    },
    shortHold: {
      id: "short_hold",
      label: "Did not hold at the top",
      severity: "minor",
      invalidatesRep: true,
      landmarks: [{ joint: "elbow" }, { joint: "wrist" }],
      low: {
        show: "Hold a little longer",
        observation: "there was no pause at the top of the movement",
        texts: [
          "Hold your hand at the top of the curl for a moment.",
          "Pause with your elbow bent and count to two before lowering.",
          "Hold your arm steady at the top for the time your therapist set.",
        ],
      },
      ack: "Good, that was a steady hold.",
    },
    incompleteReturn: {
      id: "incomplete_return",
      label: "Did not lower fully",
      severity: "minor",
      invalidatesRep: false,
      landmarks: [{ joint: "elbow" }, { joint: "wrist" }],
      high: {
        show: "Lower your arm fully",
        observation: "the arm was not lowered back to the starting position",
        texts: [
          "Lower your arm all the way down before the next curl.",
          "Let your arm hang straight down at the bottom of each curl.",
          "Finish lowering your arm slowly until it is straight.",
        ],
      },
    },
  },
  rules: [
    {
      id: "elbow_drift",
      label: "Elbow drifting away from the body",
      kind: "compensation",
      metric: "upperArm",
      phases: ["out", "peak", "back"],
      max: 28,
      release: 5,
      sustainMs: 500,
      recoverMs: 300,
      severity: "moderate",
      invalidatesRep: true,
      landmarks: [{ joint: "elbow" }, { joint: "shoulder" }],
      bones: [[{ joint: "shoulder" }, { joint: "elbow" }]],
      high: {
        show: "Keep elbow by your side",
        observation: "the elbow is swinging away from the side of the body",
        texts: [
          "Your elbow is drifting. Keep it close to your side as you curl.",
          "Tuck your elbow in by your ribs and let only your forearm move.",
          "Slow down and keep your elbow still against your side.",
        ],
      },
      ack: "Good correction, your elbow is steady.",
    },
    {
      id: "trunk_lean",
      label: "Leaning the trunk",
      kind: "alignment",
      metric: "trunk",
      phases: ["out", "peak", "back"],
      max: 18,
      release: 4,
      sustainMs: 500,
      recoverMs: 300,
      severity: "moderate",
      invalidatesRep: true,
      landmarks: [{ joint: "shoulder" }, { joint: "hip" }],
      bones: [[{ joint: "shoulder" }, { joint: "hip" }]],
      high: {
        show: "Sit tall",
        observation: "the upper body is leaning instead of staying upright",
        texts: [
          "You are leaning. Sit tall and keep your shoulders over your hips.",
          "Keep your back upright and let only your arm do the work.",
          "Slow the curl down and stay tall through your back.",
        ],
      },
      ack: "Good correction, you are sitting tall.",
    },
  ],
  validity: {
    tempoFloorMs: 800,
    holdTolerance: 0.8,
    lowToleranceMs: 1000,
    rationale: {
      minRange: "A good rep is one where the elbow bends to 72 degrees or less (a full curl). Engineering default, not tuned on real footage.",
      almostBand: "The old halfway-credit line is now only the 'almost there' band, so the wording can say a little farther. That line is at 95 degrees: past it the curl is nearly there.",
      setup: "The starting position is held for about a second so the person's own resting position is captured before any rep is judged.",
      tempoFloor: "A whole cycle faster than 0.8 seconds is flicked through, not performed. This is half of the coaching pace and the only new mandatory tempo rule.",
      hold: "A hold is mandatory only when one is required: the template's own, or the hold the therapist prescribed, with 20% tolerance so a slight early release is not punished.",
      return: "A rep ends only when the movement returns to the starting zone, so a return is always required; a very slow return is coached, not rejected.",
      visibility: "If the camera cannot see the movement for more than a second of a cycle (a third of a second when the rep fell short, so a missed peak is never blamed on the person), or cannot check a mandatory rule, the cycle is 'not seen', never wrong.",
      elbow_drift: "A swinging elbow lets the shoulder do the work of the elbow; 28 degrees of upper-arm swing is clearly visible on camera.",
      trunk_lean: "Leaning back to heave the weight up changes the exercise; 18 degrees from upright is clearly visible.",
    },
    source: "engineering-default",
  },
  statusJoints: [
    { label: "Shoulder", ref: { joint: "shoulder" } },
    { label: "Elbow", ref: { joint: "elbow" } },
    { label: "Wrist", ref: { joint: "wrist" } },
  ],
  commonMistakes: ["Swinging the elbow forward", "Leaning back to lift", "Dropping the arm quickly", "Stopping short of the top"],
};
