import type { MovementTemplate } from "../schema";

/**
 * Shoulder Abduction (lateral raise). Camera in front, both arms and shoulders in view. Primary
 * metric: how far the upper arm is lifted away from the side, as the angle between the upper
 * arm and straight down (about 10 degrees at rest, about 90 at shoulder height). The arm is
 * expected to stay close to straight; the shoulder should not shrug up toward the ear.
 */
export const shoulderAbduction: MovementTemplate = {
  id: "shoulder-abduction",
  version: 1,
  name: "Shoulder Abduction",
  description: "Lift your arm out to the side up to shoulder height, then lower it slowly. Works the muscles that raise the arm.",
  category: "Upper Body",
  difficulty: "Beginner",
  bodyPart: "Shoulder",
  bodySegment: "upper",
  primaryJoint: "shoulder",
  movement: "abduction",
  defaultReps: 10,
  instructions: [
    "Stand or sit tall facing the camera with your arms relaxed at your sides.",
    "Keep your arm nearly straight and lift it out to the side, up to shoulder height.",
    "Keep your shoulder relaxed and down, away from your ear.",
    "Lower your arm slowly back to your side.",
  ],
  camera: {
    view: "front",
    minBodyFraction: 0.15,
    maxBodyFraction: 0.85,
    hint: "Front view, about 1.5 to 2.5 m away, so both shoulders and the whole arm are in view.",
    segmentWord: "arm",
  },
  sideMode: "auto",
  landmarks: {
    required: [{ joint: "shoulder" }, { joint: "elbow" }, { joint: "wrist" }],
    optional: [{ joint: "hip" }, { joint: "ear" }],
  },
  metrics: {
    arm: { kind: "fromVertical", a: { joint: "shoulder" }, b: { joint: "elbow" } },
    elbow: { kind: "angle", a: { joint: "shoulder" }, b: { joint: "elbow" }, c: { joint: "wrist" } },
    shrug: { kind: "offsetY", point: { joint: "ear" }, from: { joint: "shoulder" }, scale: "shoulderWidth", baseline: "delta" },
    trunk: { kind: "fromVertical", a: { joint: "shoulder" }, b: { joint: "hip" } },
  },
  setup: {
    instruction: "Stand or sit tall facing the camera, with your arms relaxed at your sides.",
    holdMs: 1000,
    stableWithin: 0.05,
    conditions: [{ metric: "arm", max: 30 }],
  },
  phaseLabels: { rest: "Arm down", out: "Lifting", peak: "At shoulder height", back: "Lowering" },
  phaseCues: {
    rest: "Ready. Lift your arm out to the side.",
    out: "Keep lifting, arm nearly straight.",
    peak: "Good. Hold briefly, then lower slowly.",
    back: "Lower your arm slowly to your side.",
  },
  rep: {
    metric: "arm",
    direction: "increase",
    restThreshold: 25,
    leaveThreshold: 33,
    countThreshold: 70,
    peakThreshold: 85,
    returnDrop: 8,
    minRepMs: 2000,
    maxRepMs: 14000,
    debounceMs: 800,
    returnStallMs: 3500,
    abandonMs: 25000,
    unit: "deg",
  },
  repRules: {
    range: {
      id: "insufficient_raise",
      label: "Arm not lifted high enough",
      severity: "minor",
      invalidatesRep: true,
      landmarks: [{ joint: "elbow" }, { joint: "wrist" }],
      bones: [[{ joint: "shoulder" }, { joint: "elbow" }]],
      low: {
        observation: "the arm stopped below the target height",
        texts: [
          "Lift your arm a little higher, up toward shoulder height.",
          "Raise your elbow out to the side until your arm is about level with your shoulder.",
          "Take your time and lift your arm as high as is comfortable, up to shoulder height.",
        ],
      },
      ack: "Good, that lift went higher.",
    },
    tooFast: {
      id: "too_fast",
      label: "Moved too quickly",
      severity: "minor",
      invalidatesRep: false,
      landmarks: [{ joint: "elbow" }],
      low: {
        observation: "the arm movement was quicker than the controlled pace",
        texts: [
          "Slow down. Take about two seconds to lift your arm.",
          "Lower your arm more slowly and keep control all the way down.",
          "Count two seconds as your arm lifts and two as it lowers.",
        ],
      },
      ack: "Nice, that was a controlled pace.",
    },
    incompleteReturn: {
      id: "incomplete_return",
      label: "Did not lower fully",
      severity: "minor",
      invalidatesRep: false,
      landmarks: [{ joint: "elbow" }, { joint: "wrist" }],
      high: {
        observation: "the arm was not lowered back to the side",
        texts: [
          "Lower your arm all the way to your side before lifting again.",
          "Let your arm rest by your side at the bottom of each lift.",
          "Finish lowering your arm slowly until it hangs by your side.",
        ],
      },
    },
  },
  rules: [
    {
      id: "arm_too_high",
      label: "Arm lifted above shoulder height",
      kind: "range",
      metric: "arm",
      phases: ["out", "peak"],
      max: 105,
      release: 8,
      sustainMs: 400,
      recoverMs: 300,
      severity: "moderate",
      invalidatesRep: true,
      landmarks: [{ joint: "elbow" }, { joint: "wrist" }],
      bones: [[{ joint: "shoulder" }, { joint: "elbow" }]],
      high: {
        observation: "the arm went above shoulder height",
        texts: [
          "Lower your arm a little. Stop when it is level with your shoulder.",
          "Stop your lift at shoulder height and keep your arm out to the side.",
          "Slow down and stop the lift once your arm reaches shoulder height.",
        ],
      },
      ack: "Good correction, that is shoulder height.",
    },
    {
      id: "shoulder_shrug",
      label: "Shoulder lifting toward the ear",
      kind: "compensation",
      metric: "shrug",
      phases: ["out", "peak", "back"],
      max: 0.12,
      release: 0.03,
      sustainMs: 500,
      recoverMs: 300,
      severity: "moderate",
      invalidatesRep: true,
      landmarks: [{ joint: "shoulder" }, { joint: "ear" }],
      high: {
        observation: "the shoulder is rising toward the ear",
        texts: [
          "Keep your shoulder relaxed and down, away from your ear, as your arm lifts.",
          "Let your shoulder drop and lift only from your arm.",
          "Slow down and keep your shoulder low and relaxed through the lift.",
        ],
      },
      ack: "Good correction, your shoulder is relaxed.",
    },
    {
      id: "elbow_bent",
      label: "Elbow bending during the lift",
      kind: "compensation",
      metric: "elbow",
      phases: ["out", "peak"],
      min: 145,
      release: 8,
      sustainMs: 600,
      recoverMs: 300,
      severity: "minor",
      invalidatesRep: false,
      landmarks: [{ joint: "elbow" }],
      bones: [[{ joint: "elbow" }, { joint: "wrist" }]],
      low: {
        observation: "the elbow is bending instead of the arm staying nearly straight",
        texts: [
          "Keep your arm nearly straight as you lift it out to the side.",
          "Straighten your elbow a little and lead the lift with your hand.",
          "Slow down and keep your elbow long as your arm rises.",
        ],
      },
    },
    {
      id: "trunk_lean",
      label: "Leaning the trunk",
      kind: "alignment",
      metric: "trunk",
      phases: ["out", "peak", "back"],
      max: 15,
      release: 4,
      sustainMs: 600,
      recoverMs: 300,
      severity: "moderate",
      invalidatesRep: true,
      landmarks: [{ joint: "shoulder" }, { joint: "hip" }],
      bones: [[{ joint: "shoulder" }, { joint: "hip" }]],
      high: {
        observation: "the upper body is leaning to the side",
        texts: [
          "You are leaning to the side. Stay tall and let only your arm move.",
          "Keep your body upright and your shoulders level as your arm lifts.",
          "Slow down and stand tall through your whole body.",
        ],
      },
      ack: "Good correction, you are standing tall.",
    },
  ],
  statusJoints: [
    { label: "Shoulder", ref: { joint: "shoulder" } },
    { label: "Elbow", ref: { joint: "elbow" } },
    { label: "Wrist", ref: { joint: "wrist" } },
  ],
  commonMistakes: ["Shrugging the shoulder", "Lifting above shoulder height", "Bending the elbow", "Leaning away to lift"],
};
